version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: vue-i18n
    versions:
    - 8.22.4
    - 8.23.0
    - 8.24.1
    - 8.24.2
  - dependency-name: vue-router
    versions:
    - 3.4.9
  - dependency-name: electron
    versions:
    - 9.3.1
  - dependency-name: electron-builder
    versions:
    - 22.9.1
  - dependency-name: electron-updater
    versions:
    - 4.3.5
  - dependency-name: elliptic
    versions:
    - 6.5.3
