matrix:
  include:
  - os: linux
    language: node_js
    node_js: '10'
    script:
    - make .publish-admin-linux
  - os: windows
    language: node_js
    node_js: '10'
    before_install:
    - choco install -y make
    before_cache:
      - rmdir $HOME\AppData\Local\electron-builder\Cache /S /Q
    script:
    - make .publish-admin-win
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
